### ISSUE TITLE
Cannot make this extension work at all

### ISSUE THREAD

**Issue by mxmrlt** [srfrnk/vsc-user-extensions#1]
Hi.

Under Ubuntu 17.10 and VS Code 1.18.1...

Here's the console output.

Updating settings...

/usr/share/code/resources/app/out/vs/code/node/cli.js:4
(function(){var e=["exports","require","vs/base/common/winjs.base","vs/base/common/platform","path","vs/base/common/uri","vs/base/common/event","vs/base/common/errors","vs/base/common/types","vs/base/common/lifecycle","fs","vs/base/common/functional","os","vs/platform/node/product","vs/base/common/arrays","vs/base/common/objects","vs/base/common/callbackList","vs/base/common/cancellation","vs/base/common/map","vs/base/common/async","vs/base/node/flow","assert","vs/base/node/extfs","vs/base/common/strings","vs/base/common/uuid","vs/base/node/pfs","vs/base/common/linkedList","vs/nls!vs/platform/environment/node/argv","vs/platform/node/package","vs/platform/environment/node/argv","vs/nls!vs/code/node/cli","minimist","vs/nls","vs/base/common/winjs.base.raw","vs/code/node/cli","child_process"],t=function(t){for(var n=[],r=0,i=t.length;r<i;r++)n[r]=e[t[r]];return n};define(e[11],t([1,0]),function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:
Failed to watch /home/mrault/.config/Code/User for configuration changes (Error: watch /home/mrault/.config/Code/User ENOSPC)

Ready...
Ready...

/usr/share/code/resources/app/out/vs/code/node/cli.js:4
(function(){var e=["exports","require","vs/base/common/winjs.base","vs/base/common/platform","path","vs/base/common/uri","vs/base/common/event","vs/base/common/errors","vs/base/common/types","vs/base/common/lifecycle","fs","vs/base/common/functional","os","vs/platform/node/product","vs/base/common/arrays","vs/base/common/objects","vs/base/common/callbackList","vs/base/common/cancellation","vs/base/common/map","vs/base/common/async","vs/base/node/flow","assert","vs/base/node/extfs","vs/base/common/strings","vs/base/common/uuid","vs/base/node/pfs","vs/base/common/linkedList","vs/nls!vs/platform/environment/node/argv","vs/platform/node/package","vs/platform/environment/node/argv","vs/nls!vs/code/node/cli","minimist","vs/nls","vs/base/common/winjs.base.raw","vs/code/node/cli","child_process"],t=function(t){for(var n=[],r=0,i=t.length;r<i;r++)n[r]=e[t[r]];return n};define(e[11],t([1,0]),function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:
Failed to watch /home/mrault/.config/Code/User for configuration changes (Error: watch /home/mrault/.config/Code/User ENOSPC)

**Comment by srfrnk** [comment]
hi,
first check that you have free space on the device. (ENOSPC means no space left)
if that's not the problem it might be this known issue with [nodejs watch on linux](http://lmgtfy.com/?q=ENOSPC+watch+nodejs+linux), running this might help:
```bash
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
hope that works.

**Comment by mxmrlt** [comment]
Indeed it did the trick. Thank you.
