### ISSUE TITLE
extensions.recommendations: Incorrect type. Expected "Array<string>"

### ISSUE THREAD

**Issue by vith** [srfrnk/vsc-user-extensions#2]
This is a warning, not an error, but it gets in the way of navigating between actual problems in the projects I have open (with <kbd>F8</kbd>, etc.).

**Comment by srfrnk** [comment]
Can you specify the steps to reproduce?
Where exactly are you seeing this warning?
Is there a stack trace?

**Comment by srfrnk** [comment]
Please update to 1.0.3

**Comment by vith** [comment]
That worked, thanks!
